enabled: true
name: graduation-success
image: alexlopef15/flask-app:rev1
port: 5000
resources:
  replicas: 1
  instanceType: A4000
env:
  - name: FLASK_ENV
    value: production
  - name: SECRET_KEY
    value: its-been-years-2017
